### ISSUE TITLE
Python 3.6 support is broken

### ISSUE THREAD

**Issue by ampledata** [ampledata/adsbxcot#6]
```
[admin@takserver ~]$ adsbxcot
Traceback (most recent call last):
  File "/usr/local/bin/adsbxcot", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/adsbxcot/commands.py", line 134, in cli
    loop = get_event_loop()
NameError: name 'get_event_loop' is not defined
```

**Comment by ampledata** [comment]
Line 25 of commands.py reads:
```
    from asyncio import _get_running_loop as get_running_loop
```
See: https://github.com/ampledata/adsbxcot/blob/main/adsbxcot/commands.py#L25

It should read:
```
    from asyncio import get_event_loop as get_running_loop
```
